ingress-nginx:
  controller:
    replicaCount: 2
    ingressClass: nginx
    ingressClassResource:
      enabled: true
      name: nginx
      default: true
    watchIngressWithoutClass: true
    publishService:
      enabled: true
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      LoadBalancerIP: 192.168.1.230